# Generated by Django 3.1.5 on 2021-05-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_timer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timer',
        ),
    ]
